# Generated by Django 5.0.6 on 2024-09-08 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment_link_payment_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_sum',
            new_name='amount',
        ),
    ]
