# Generated by Django 5.0.6 on 2024-09-08 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_payment_sum_payment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_lesson',
            new_name='lesson',
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
