# Generated by Django 5.0.6 on 2024-08-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_course',
            field=models.ImageField(blank=True, help_text='Загрузите превью курса', null=True, upload_to='materials/course', verbose_name='Превью курса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image_course',
            field=models.ImageField(blank=True, help_text='Загрузите превью урока', null=True, upload_to='materials/lesson', verbose_name='Превью урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Загрузите видео урока', max_length=300, null=True, verbose_name='Видео урока'),
        ),
    ]
